# ===================================================================
# CONFIGURAÇÕES DO SERVIDOR
# ===================================================================
server.port=8080
spring.application.name=Simulador-de-Encomendas-em-Drone

# ===================================================================
# CONFIGURAÇÕES DO BANCO DE DOS (POSTGRESQL)
# ===================================================================
# Substitua 'localhost:5432/seu_banco' pelo caminho e nome do seu banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/simulador_drones
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===================================================================
# 'update' cria as tabelas automaticamente se elas não existirem e altera caso o model mude
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries SQL executadas no console (Excelente para monitorar a SimulacaoEngine)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURAÇÕES DE HORA E IDIOMA (JACKSON)
# ===================================================================
# Garante que as datas geradas nos DTOs sigam o padrão ISO local brasileiro
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.serialization.write-dates-as-timestamps=false

# ===================================================================
# CONFIGURAÇÕES DE LOG
# ===================================================================
# Define o nível de log para a sua aplicação conseguir ver os disparos do @Slf4j
logging.level.com.example.Simulador_de_Encomendas_em_Drone=INFO