version: '3.8'

services:
  # --- BANCO DE DADOS (POSTGRESQL 16) ---
  db:
    image: postgres:16-alpine
    container_name: simulador_db
    restart: always
    environment:
      POSTGRES_DB: simulador_drones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simulador_drones"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BACKEND (SPRING BOOT - JAVA 21) ---
  backend:
    build:
      context: ./backend/Simulador-de-Encomendas-em-Drone
      dockerfile: Dockerfile
    container_name: simulador_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/simulador_drones
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      db:
        condition: service_healthy

  # --- FRONTEND (NEXT.JS) ---
  frontend:
    build:
      context: ./frontend # Ajuste para o caminho correto da pasta do seu Frontend
      dockerfile: Dockerfile
    container_name: simulador_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api
    depends_on:
      - backend

volumes:
  postgres_data: